Verify .so linking (nvbufsurf doesn't work), fix glib and gst import
parallelsystems/deepstream-sys pull request #1
Opened 2022-05-13 21:53 UTC by patmryan

# Background

We want to be able to automatically create rust bindings for the deepstream libraries we are using. We tell bindgen the .h files that need to be rustified, and we also tell bindgen the .so files to be used. It has not yet been tested whether this linking was correct. Also, the libraries for which we are creating bindings rely on glib and gst libraries, for which there are already crates containing bindings (that we would like to use). Hence, we need to find a way to tell bindgen to recognize the types that are defined in these libraries without actually creating new bindings for them because we don't want to create bindings for, say, the same function twice.

# Description

I wrote tests corresponding to each .h file that we wrote bindings for in order to verify that they are being properly bound. I also got it so that we can utilize glib and gstreamer libraries without recreating bindings for them.

# Verification

The tests that I wrote pass (with the exception of one that I wrote and have left a comment on). For the second task, I verified that the code builds without incident and that the pre-existing crates are being used. Furthermore, I checked the bindings and the .h files being bound to ensure that no conflict would occur with the pre-existing crates (glib. glib-sys, and gstreamer-sys).

2022-05-13 21:53 UTC, patmryan commented on build.rs
> +    println!(r"cargo:rustc-link-lib=yolo");
Should I delete the links to .so file we do not actually use?

2022-05-13 21:56 UTC, patmryan commented on tests/integration_tests.rs
> +// this one is not properly linked, but I cannot find the .so file where NvBufSurfaceCreate is
I left this code commented out because as of right now, I can not find the linked file, so this test fails.

2022-05-13 22:02 UTC, jswang commented on build.rs
> +    println!(r"cargo:rustc-link-lib=yolo");
We want to build out this library to include bindings for all of the deepstream libraries, so let's leave these in.

2022-05-13 22:09 UTC, jswang requested changes

2022-05-13 22:09 UTC, jswang commented on src/lib.rs
> +pub type guint8 = ::std::os::raw::c_uchar;
where did these definitions come from? Ideally we should include the file that has these definitions rather than copying them in again.

2022-05-13 22:09 UTC, jswang commented on tests/integration_tests.rs
> +// #[test]
Can you leave a comment about how this is broken in deepstream 5.0 with a link to the forum post you found?

2022-05-13 22:09 UTC, jswang commented on tests/integration_tests.rs
> +// do not need to be mutable. However, when mut is removed, the compiler throws an error.
This should be fixed, you might need to do some casts

2022-05-13 22:16 UTC, patmryan commented on src/lib.rs
> +pub type guint8 = ::std::os::raw::c_uchar;
They come from glib.h. The bindings contained in the preexisting glib crates we are using are pretty much exactly the same as ours, except for they don't define these types but just use things like `c_int` instead. I could maybe try to do away with blocking the entire file (calling `blocklist_file`) and only include these types.

2022-05-13 22:24 UTC, patmryan commented on tests/integration_tests.rs
> +// #[test]
I should clarify that the bug was with `gst_buffer_get_nvds_meta`. I have left a comment above the `test_gstnvdsmeta` function (updated to include a link to the forum post) noting the bug. 

For this particular test, I actually could not find the .so file. I looked through the `/opt/nvidia/deepstream/deepstream-5.0/lib` directory and saw (using `nm`) that the functions from this .h file were not defined anywhere in these .so files. I was, however, able to call these functions from c code, so it exists somewhere.

2022-05-13 22:58 UTC, stabler commented on tests/integration_tests.rs
> +    let buff = unsafe { gst_buffer_new() };
Do these tests clean up allocated objects properly? The test will exit soon after so presumably memory will be dumped.. but still good practice to do a clean teardown

2022-05-16 17:49 UTC, jswang requested changes

2022-05-16 17:49 UTC, jswang commented on tests/integration_tests.rs
> +    let success = unsafe { NvBufSurfaceCreate(dub_ptr, 1, create_params) };
Is there a corresponding `NvBufSurfaceDestroy` function that needs to be called?

2022-05-16 17:49 UTC, jswang commented on build.rs
> +
nitpick: does this line space need to exist?

2022-05-16 17:49 UTC, jswang commented on src/lib.rs
> +pub type guint8 = ::std::os::raw::c_uchar;
ok, yeah let's try and get rid of this copypasta if we can

2022-05-16 17:49 UTC, jswang commented on tests/integration_tests.rs
> +    unsafe { NvDsSRCreate(ctx, params) };
Is there a corresponding destroy that should be getting called?

2022-05-16 20:21 UTC, patmryan commented on src/lib.rs
> +pub type guint8 = ::std::os::raw::c_uchar;
Could you let me know what exactly is the reason we don't want copypasta? I have had a bit of trouble finding exactly where these types are defined, and so my thought is to just create a .h file with them defined and then include this in the binding, but I don't know if this would be just as problematic as copying and pasting into the lib file.

2022-05-16 20:21 UTC, patmryan commented on tests/integration_tests.rs
> +    let buff = unsafe { gst_buffer_new() };
addressed.

2022-05-17 21:38 UTC, jswang requested changes

2022-05-17 21:38 UTC, jswang commented on build.rs
> +        .blocklist_type(r".*Gst.*")
Won't this also block valid nvidia types? for example, there is `_GstNvDsBufferPool` and `GstNvDsMetaType`

2022-05-17 21:38 UTC, jswang commented on src/lib.rs
> +pub type guint8 = ::std::os::raw::c_uchar;
talked offline, if things get out of sync, this hardcoding wouldn't capture it

2022-05-17 23:46 UTC, jswang approved these changes

2022-05-18 00:01 UTC, merged